### PR TITLE
fix bug of link is definded but not used

### PR DESCRIPTION
**Pull request by hzfhhh**
Please makes sure the items are checked before submitting your PR, thank you!

* [x] `Rebase` before creating a PR to keep commit history clear.
* [x] `Only One commit`
* [x] No `eslint` errors

### CODE REVIEW

**Review by lichunqiang — COMMENTED** [review]
其实是有用到的：
https://github.com/hzfhhh/vux/blob/a22d6b36a6/src/mixins/multi-items.js#L74

**Comment by airyland** [comment]
有用到的。这样改的话呢，就无法支持vue-router的跳转参数了。

**Comment by hzfhhh** [comment]
那为什么按照文档的写法link没起作用呢？
```
<tabbar-item selected link="/component/demo">
 <img slot="icon" src="../assets/demo/icon_nav_article.png">
 <span slot="label">Explore</span>
</tabbar-item>
```

**Comment by hzfhhh** [comment]
抱歉，组件的代码没问题，是我自己的项目问题导致onItemClick()没起作用，

**Pull request closed without merging**
