### PR TITLE
types: add TypeScript Support

### PR DESCRIPTION
**Pull request by doommm**
These days i'm working on a project base on `VUX` and `TypeScript`. I wrote some TS declarations to improve coding experience and reduce errors while coding, and then i create this PR and hope to help anyone uses `TypeScript`.

By the way, this is a alpha?(**means very simple and incomplete**) version, and hope we could improve it together.

---
Please makes sure the items are checked before submitting your PR, thank you!

* [x] `Rebase` before creating a PR to keep commit history clear.
* [x] `Only One commit`
* [x] No `eslint` errors

### CODE REVIEW

**Comment by zongzi531** [comment]
Now PR is not be Merged, i can declare module in shims-vue.d.ts. but, how do you solve @vue/cli 3.x and vux-loader problem?

**Comment by doommm** [comment]
@zongzi531 What problem do you have? I didn't use @vue/cli 3 and have no idea about what problems we may have.

**Comment by zongzi531** [comment]
@doommm Ok, I thought you used @vue/cli 3.x

**Comment by zongzi531** [comment]
@doommm I saw that commit https://github.com/airyland/vux/commit/94c5ab787bc01c2fbbcd171d233d3221003c8727

**Comment by wangxv** [comment]
支持typeScript的版本是不是还没有发布？

**Comment by caozhong1996** [comment]
非常感谢，但是目前精力有限，如非必要不再提供新的feature了（确实没精力），vux-loader相关的问题将会在2.9.5修复，完备的ts支持会在下个大版本提供，再次感谢。

**Pull request closed without merging**
